config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  get 'auth/:provider/callback' => 'sessions#create'
  get '/signout'     => 'sessions#destroy', :as => :signout
  get   'profile'  => 'sessions#edit',  :as => :edit_profile
  patch 'update/:id'  => 'sessions#update',   :as =>  :update_profile

  resources :dashboard
  resources :members
  resources :about


  root 'site#index'
  mount Sidekiq::Web, at: "/sidekiq"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate!

  def index

    @organization = Organization.where(id: params[:organization]).try(:first) || current_user.organizations.where(aasm_state: 'completed').try(:first)
    if @organization
      params[:organization] = @organization.id
      if current_user.organizations.where("aasm_state like 'fetching'").size > 0 && !@organization.fetching?
        flash[:alert] = "You can only process one organization at the time."
      elsif @organization.created?
        if @organization.name != 'railsrumble'
          @organization.move_to_queue(session[:user_token], current_user)
          flash[:alert] = nil
        else
          flash[:alert] = "I'll love to process this organization but I'm worry about the size :p"
        end
      end
    end

    flash[:info] = "Start by selecting one of your organization." unless current_user.organizations.where("aasm_state like 'completed'").any?
  end

  def show
  end


end

app/views/dashboard/_organization_stats.html.haml
.row
  .col-md-3.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-aqua
        %i.fa.fa-code
      .info-box-content
        %span.info-box-text Merged Pull Requests
        %span.info-box-number= @organization.merged_pull_requests
      / /.info-box-content
    / /.info-box
  / /.col
  .col-md-3.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-green
        %i.fa.fa-code-fork
      .info-box-content
        %span.info-box-text Open Pull Requests
        %span.info-box-number= @organization.open_pull_requests
      / /.info-box-content
    / /.info-box
  / /.col
  .col-md-3.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-yellow
        %i.fa.fa-github-square
      .info-box-content
        %span.info-box-text Repositories
        %span.info-box-number= @organization.repository_count
      / /.info-box-content
    / /.info-box
  / /.col
  .col-md-3.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-red
        %i.fa.fa-users
      .info-box-content
        %span.info-box-text Members
        %span.info-box-number= @organization.members.count

%h3 Top Repositories
.row
  - @organization.repository_rank.each do |repo|
    .col-md-3.col-sm-6.col-xs-12
      .info-box.reposistories
        %span.info-box-icon
          %i.fa.fa-folder-o
        .info-box-content
          %span.info-box-text= repo.last.name
          %span.info-box-number
            %b Pull Requests:
            = repo.first

%h3 Ranked Members
.row
  - @organization.rank_members.each do |member|
    .col-md-3
      .box.box-widget.widget-user
        .widget-user-header.bg-aqua-active
          %h3.widget-user-username= link_to member.name, member_path(member)
        .widget-user-image
          = image_tag member.avatar, class: 'img-circle'
        .box-footer
          .row
            .col-sm-4.border-right
              .description-block
                %h5.description-header= member.open_pull_requests_count
                %span.description-text OPEN PULL REQUEST
            .col-sm-4.border-right
              .description-block
                %h5.description-header= member.pull_requests_weight.round(2)
                %span.description-text= link_to "CONTRIBUTRON SCORE", about_index_path(anchor: 'score')
            .col-sm-4
              .description-block
                %h5.description-header= member.merged_pull_requests_count
                %span.description-text MERGED PULL REQUEST

%h3 Members
.row
  - @organization.no_rank_members.each do |member|
    .col-md-4
      / Widget: user widget style 1
      .box.box-widget.widget-user-2
        / Add the bg color to the header using any of the bg-* classes
        .widget-user-header.bg-yellow
          .widget-user-image
            = image_tag member.avatar, class: 'img-circle'
          / /.widget-user-image
          %h3.widget-user-username= link_to member.name, member_path(member, organization: params[:organization])
          %h5.widget-user-desc
            %b Contribution Score:
            = member.pull_requests_weight.round(2)
            %b Merged PRs:
            = member.merged_pull_requests_count
            %b Open PRs:
            = member.open_pull_requests_count

app/views/dashboard/index.html.haml
- content_for :page_title do
  Dashboard
  = " - #{@organization.try(:name).try(:capitalize)}"

- if @organization.try(:fetching?)
  .box
    .box-header.with-border
      %h3.box-title
      .box-tools.pull-right
        %button.btn.btn-box-tool{"data-toggle" => "tooltip", "data-widget" => "collapse", :title => "Collapse", :type => "button"}
          %i.fa.fa-minus
        %button.btn.btn-box-tool{"data-toggle" => "tooltip", "data-widget" => "remove", :title => "Remove", :type => "button"}
          %i.fa.fa-times
    .box-body
      %h1
        Getting data for
        = @organization.name
        %p give us a moment to query necesary data from Big Query.
      %p Please reload the page in like 2 minutes or wait for an email from us.
    .box-footer

= render partial: 'dashboard/organization_stats' if @organization.try(:completed?)

- if @organization.nil?
  .box
    .box-header.with-border
      %h3.box-title
      .box-tools.pull-right
        %button.btn.btn-box-tool{"data-toggle" => "tooltip", "data-widget" => "collapse", :title => "Collapse", :type => "button"}
          %i.fa.fa-minus
        %button.btn.btn-box-tool{"data-toggle" => "tooltip", "data-widget" => "remove", :title => "Remove", :type => "button"}
          %i.fa.fa-times
    .box-body
      %h1
        Thanks for login,
      %p To see information about the desired organization, start by selecting one in the left dropdown and click on the button next to it.

app/views/dashboard/show.html.haml
%h1 DashboardController#show
%p Find me in app/views/dashboard_controller/show.html.haml