config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  get 'auth/:provider/callback' => 'sessions#create'
  get '/signout'     => 'sessions#destroy', :as => :signout
  get   'profile'  => 'sessions#edit',  :as => :edit_profile
  patch 'update/:id'  => 'sessions#update',   :as =>  :update_profile

  resources :dashboard
  resources :members
  resources :about


  root 'site#index'
  mount Sidekiq::Web, at: "/sidekiq"
end

app/views/elements/_flash_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - name = "success" if name == "notice"
    - name = "danger" if name == "alert"
    %div{:class => "alert alert-#{name} alert-dismissible"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      %h4
        %i.icon.fa.fa-info
        = "#{name.capitalize}!"
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/elements/_side_bar.html.haml
/ Left side column. contains the sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel
    .user-panel
      .pull-left.image
        = image_tag current_user.avatar, class: 'img-circle'
      .pull-left.info
        %p= current_user.name

    = form_tag '/dashboard', method: :get, class: 'sidebar-form' do
      .input-group
        = select_tag( :organization, options_from_collection_for_select(@organizations, 'id', 'name', params[:organization]), class: 'form-control')
        .input-group-btn
          %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
            %i.fa.fa-exchange

    / sidebar menu: : style can be found in sidebar.less
    %ul.sidebar-menu
      %li.header MAIN NAVIGATION
      %li.treeview
        = link_to dashboard_index_path(organization: params[:organization]) do
          %i.fa.fa-dashboard
          %span Dashboard
      %li
        = link_to about_index_path do
          %i.fa.fa-book
          About Contributron

app/views/elements/_top_nav.html.haml
%header.main-header
  / Logo
  %a.logo{:href => "../../index2.html"}
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      = image_tag 'white-contributron.svg', width: '30'
    / logo for regular state and mobile devices
    %span.logo-lg
      = image_tag 'white-contributron.svg', width: '30'
      %b>  Contribu
      tron
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-custom-menu
      %ul.nav.navbar-nav

        / User Account: style can be found in dropdown.less
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = image_tag current_user.avatar, class: 'user-image', with: 160, height: 160
            %span.hidden-xs= current_user.username
          %ul.dropdown-menu
            / User image
            %li.user-header
              = image_tag current_user.avatar, class: 'img-circle'
              %p
                = current_user.name
                = "- Web Developer"
                %small
                  Member since
                  = time_ago_in_words(current_user.created_at)

            / Menu Footer
            %li.user-footer
              .pull-left
                = link_to "Profile", edit_profile_path, class: 'btn btn-default btn-flat'
              .pull-right
                %a.btn.btn-default.btn-flat{:href => "/signout"} Sign out
        / Control Sidebar Toggle Button
        %li
          = link_to edit_profile_path do
            %i.fa.fa-gears